// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCr03McxrvHJzwU7eHcI-ruzP_H6DXUDZ0',
    appId: '1:712809660405:web:ff8f29d6c4a7f4539aeabc',
    messagingSenderId: '712809660405',
    projectId: 'casestudy2itnan-group',
    authDomain: 'casestudy2itnan-group.firebaseapp.com',
    storageBucket: 'casestudy2itnan-group.appspot.com',
    measurementId: 'G-H3D5QEB3CZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMP_IpjbdCFgLRyebiZJa38nnplRmylCs',
    appId: '1:712809660405:android:5f69864ac712e5ff9aeabc',
    messagingSenderId: '712809660405',
    projectId: 'casestudy2itnan-group',
    storageBucket: 'casestudy2itnan-group.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVMBMxtWSP7vSFWiCdopC8p6aSBrbhaDM',
    appId: '1:712809660405:ios:969e899f49fe3c2c9aeabc',
    messagingSenderId: '712809660405',
    projectId: 'casestudy2itnan-group',
    storageBucket: 'casestudy2itnan-group.appspot.com',
    iosClientId: '712809660405-kho175dbc345jnvlpfopq2lmm3p396hj.apps.googleusercontent.com',
    iosBundleId: 'com.example.cstdt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVMBMxtWSP7vSFWiCdopC8p6aSBrbhaDM',
    appId: '1:712809660405:ios:969e899f49fe3c2c9aeabc',
    messagingSenderId: '712809660405',
    projectId: 'casestudy2itnan-group',
    storageBucket: 'casestudy2itnan-group.appspot.com',
    iosClientId: '712809660405-kho175dbc345jnvlpfopq2lmm3p396hj.apps.googleusercontent.com',
    iosBundleId: 'com.example.cstdt',
  );
}
